AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - '**/*.erb'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'db/migrate/*'
