AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false

Bundler/OrderedGems:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Metrics/MethodLength:
  Max: 20
